# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\S.O.F.T.S\PYTHON\Pirana\src\gui\parameters_qt.ui'
#
# Created: Fri Mar 13 10:01:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

def _fromUtf8(s):
    return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget_Parameters(object):
    def setupUi(self, DockWidget_Parameters):
        DockWidget_Parameters.setObjectName(_fromUtf8("DockWidget_Parameters"))
        DockWidget_Parameters.resize(330, 315)
        DockWidget_Parameters.setMinimumSize(QtCore.QSize(330, 315))
        DockWidget_Parameters.setMaximumSize(QtCore.QSize(330, 315))
        DockWidget_Parameters.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        DockWidget_Parameters.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.groupBox_Excit = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_Excit.setGeometry(QtCore.QRect(10, 30, 311, 90))
        self.groupBox_Excit.setMinimumSize(QtCore.QSize(300, 70))
        self.groupBox_Excit.setMaximumSize(QtCore.QSize(320, 90))
        self.groupBox_Excit.setObjectName(_fromUtf8("groupBox_Excit"))
        self.label_ExcitEnd = QtGui.QLabel(self.groupBox_Excit)
        self.label_ExcitEnd.setGeometry(QtCore.QRect(240, 45, 60, 16))
        self.label_ExcitEnd.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ExcitEnd.setObjectName(_fromUtf8("label_ExcitEnd"))
        self.lineEdit_ExcitEnd = QtGui.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitEnd.setEnabled(False)
        self.lineEdit_ExcitEnd.setGeometry(QtCore.QRect(234, 65, 67, 20))
        self.lineEdit_ExcitEnd.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitEnd.setFont(font)
        self.lineEdit_ExcitEnd.setObjectName(_fromUtf8("lineEdit_ExcitEnd"))
        self.lineEdit_ExcitStart = QtGui.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitStart.setEnabled(False)
        self.lineEdit_ExcitStart.setGeometry(QtCore.QRect(161, 65, 67, 20))
        self.lineEdit_ExcitStart.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitStart.setFont(font)
        self.lineEdit_ExcitStart.setObjectName(_fromUtf8("lineEdit_ExcitStart"))
        self.label_ExcitStart = QtGui.QLabel(self.groupBox_Excit)
        self.label_ExcitStart.setGeometry(QtCore.QRect(163, 45, 65, 16))
        self.label_ExcitStart.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ExcitStart.setObjectName(_fromUtf8("label_ExcitStart"))
        self.lineEdit_ExcitType = QtGui.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitType.setEnabled(False)
        self.lineEdit_ExcitType.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.lineEdit_ExcitType.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitType.setFont(font)
        self.lineEdit_ExcitType.setObjectName(_fromUtf8("lineEdit_ExcitType"))
        self.lineEdit_ExcitIntensity = QtGui.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitIntensity.setEnabled(False)
        self.lineEdit_ExcitIntensity.setGeometry(QtCore.QRect(88, 65, 67, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitIntensity.setFont(font)
        self.lineEdit_ExcitIntensity.setObjectName(_fromUtf8("lineEdit_ExcitIntensity"))
        self.lineEdit_ExcitDuration = QtGui.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitDuration.setEnabled(False)
        self.lineEdit_ExcitDuration.setGeometry(QtCore.QRect(12, 65, 70, 20))
        self.lineEdit_ExcitDuration.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitDuration.setFont(font)
        self.lineEdit_ExcitDuration.setObjectName(_fromUtf8("lineEdit_ExcitDuration"))
        self.label_ExcitDuration = QtGui.QLabel(self.groupBox_Excit)
        self.label_ExcitDuration.setGeometry(QtCore.QRect(11, 45, 70, 16))
        self.label_ExcitDuration.setMinimumSize(QtCore.QSize(70, 0))
        self.label_ExcitDuration.setObjectName(_fromUtf8("label_ExcitDuration"))
        self.label_ExcitIntensity = QtGui.QLabel(self.groupBox_Excit)
        self.label_ExcitIntensity.setGeometry(QtCore.QRect(87, 45, 70, 16))
        self.label_ExcitIntensity.setMinimumSize(QtCore.QSize(70, 0))
        self.label_ExcitIntensity.setObjectName(_fromUtf8("label_ExcitIntensity"))
        self.groupBox_Eject = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_Eject.setGeometry(QtCore.QRect(10, 130, 311, 98))
        self.groupBox_Eject.setMinimumSize(QtCore.QSize(300, 70))
        self.groupBox_Eject.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_Eject.setObjectName(_fromUtf8("groupBox_Eject"))
        self.comboBox_EjectEnd = QtGui.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectEnd.setGeometry(QtCore.QRect(236, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectEnd.setFont(font)
        self.comboBox_EjectEnd.setObjectName(_fromUtf8("comboBox_EjectEnd"))
        self.comboBox_EjectStart = QtGui.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectStart.setGeometry(QtCore.QRect(161, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectStart.setFont(font)
        self.comboBox_EjectStart.setObjectName(_fromUtf8("comboBox_EjectStart"))
        self.label_EjectStart = QtGui.QLabel(self.groupBox_Eject)
        self.label_EjectStart.setGeometry(QtCore.QRect(164, 50, 65, 16))
        self.label_EjectStart.setObjectName(_fromUtf8("label_EjectStart"))
        self.label_EjectEnd = QtGui.QLabel(self.groupBox_Eject)
        self.label_EjectEnd.setGeometry(QtCore.QRect(240, 50, 60, 16))
        self.label_EjectEnd.setObjectName(_fromUtf8("label_EjectEnd"))
        self.comboBox_EjectIntensity = QtGui.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectIntensity.setGeometry(QtCore.QRect(86, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectIntensity.setFont(font)
        self.comboBox_EjectIntensity.setObjectName(_fromUtf8("comboBox_EjectIntensity"))
        self.label_EjectIntensity = QtGui.QLabel(self.groupBox_Eject)
        self.label_EjectIntensity.setGeometry(QtCore.QRect(87, 50, 65, 16))
        self.label_EjectIntensity.setObjectName(_fromUtf8("label_EjectIntensity"))
        self.label_EjectDuration = QtGui.QLabel(self.groupBox_Eject)
        self.label_EjectDuration.setGeometry(QtCore.QRect(11, 50, 65, 16))
        self.label_EjectDuration.setObjectName(_fromUtf8("label_EjectDuration"))
        self.comboBox_EjectName = QtGui.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectName.setGeometry(QtCore.QRect(10, 20, 81, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectName.setFont(font)
        self.comboBox_EjectName.setObjectName(_fromUtf8("comboBox_EjectName"))
        self.lineEdit_EjectType = QtGui.QLineEdit(self.groupBox_Eject)
        self.lineEdit_EjectType.setEnabled(False)
        self.lineEdit_EjectType.setGeometry(QtCore.QRect(100, 20, 70, 20))
        self.lineEdit_EjectType.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_EjectType.setFont(font)
        self.lineEdit_EjectType.setObjectName(_fromUtf8("lineEdit_EjectType"))
        self.lineEdit_EjectDuration = QtGui.QLineEdit(self.groupBox_Eject)
        self.lineEdit_EjectDuration.setEnabled(False)
        self.lineEdit_EjectDuration.setGeometry(QtCore.QRect(10, 69, 70, 20))
        self.lineEdit_EjectDuration.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_EjectDuration.setFont(font)
        self.lineEdit_EjectDuration.setObjectName(_fromUtf8("lineEdit_EjectDuration"))
        self.lineEdit_File = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit_File.setEnabled(False)
        self.lineEdit_File.setGeometry(QtCore.QRect(140, 10, 133, 20))
        self.lineEdit_File.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_File.setFont(font)
        self.lineEdit_File.setText(_fromUtf8(""))
        self.lineEdit_File.setReadOnly(False)
        self.lineEdit_File.setObjectName(_fromUtf8("lineEdit_File"))
        self.groupBox_Detect = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_Detect.setGeometry(QtCore.QRect(10, 235, 311, 51))
        self.groupBox_Detect.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_Detect.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_Detect.setObjectName(_fromUtf8("groupBox_Detect"))
        self.comboBox_DetectName = QtGui.QComboBox(self.groupBox_Detect)
        self.comboBox_DetectName.setGeometry(QtCore.QRect(10, 20, 81, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_DetectName.setFont(font)
        self.comboBox_DetectName.setObjectName(_fromUtf8("comboBox_DetectName"))
        self.label_Filename = QtGui.QLabel(self.dockWidgetContents)
        self.label_Filename.setGeometry(QtCore.QRect(70, 10, 60, 16))
        self.label_Filename.setObjectName(_fromUtf8("label_Filename"))
        DockWidget_Parameters.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_Parameters)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_Parameters)

    def retranslateUi(self, DockWidget_Parameters):
        DockWidget_Parameters.setWindowTitle(_translate("DockWidget_Parameters", "Parameters", None))
        self.groupBox_Excit.setTitle(_translate("DockWidget_Parameters", "Excitation", None))
        self.label_ExcitEnd.setText(_translate("DockWidget_Parameters", "End (MHz)", None))
        self.label_ExcitStart.setText(_translate("DockWidget_Parameters", "Start (MHz)", None))
        self.label_ExcitDuration.setText(_translate("DockWidget_Parameters", "Dura. (ms)", None))
        self.label_ExcitIntensity.setText(_translate("DockWidget_Parameters", "Intens. (%)", None))
        self.groupBox_Eject.setTitle(_translate("DockWidget_Parameters", "Ejections", None))
        self.label_EjectStart.setText(_translate("DockWidget_Parameters", "Start (MHz)", None))
        self.label_EjectEnd.setText(_translate("DockWidget_Parameters", "End (MHz)", None))
        self.label_EjectIntensity.setText(_translate("DockWidget_Parameters", "Intens. (%)", None))
        self.label_EjectDuration.setText(_translate("DockWidget_Parameters", "Dura. (ms)", None))
        self.groupBox_Detect.setTitle(_translate("DockWidget_Parameters", "Detection", None))
        self.label_Filename.setText(_translate("DockWidget_Parameters", "FILENAME", None))

